name : AdityaRDP

on : workflow_dispatch

jobs :
  build :

    runs-on : windows-latest
    timeout-minutes : 9999

    steps :
    - name : Download Ngrok.
      run : |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/loop.bat -OutFile loop.bat
    - name : Downloading Launcher.
      run : |
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/AdityaGans2542/AdityaRDP/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://github.com/AdityaGans2542/AdityaRDP/raw/main/launcher/Ganti%20Password.exe -OutFile "Change Password.exe"
    - name : Extracting File.
      run : Expand-Archive ngrok.zip
    - name : Connect to Ngrok Account.
      run : . \ ngrok \ ngrok.exe authtoken $ Env: NGROK_AUTH_TOKEN
      env :
        NGROK_AUTH_TOKEN : $ {{secrets.NGROK_AUTH_TOKEN}}
    - name : Enable RDP access.
      run : |
        Set-ItemProperty -Path 'HKLM: \ System \ CurrentControlSet \ Control \ Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM: \ System \ CurrentControlSet \ Control \ Terminal Server \ WinStations \ RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D: \ a \ wallpaper.png
        copy wallpaper.bat D: \ a \ wallpaper.bat
        copy Node.js.lnk C: \ Users \ Public \ Desktop \ Node.js.lnk
        copy "Visual Studio 2019.lnk" "C: \ Users \ Public \ Desktop \ Visual Studio 2019.lnk"
        copy "Change Password.exe" "C: \ Users \ Public \ Desktop \ Change Password.exe"
    - name : Create a Tunnel.
      run : Start-Process Powershell -ArgumentList '-Noexit -Command ". \ ngrok \ ngrok.exe tcp --region ap 3389"'
    - name : Connect to your RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run : cmd / c start.bat
    - name : Created successfully! You Can Close Tab Now.
      run : cmd / c loop.bat
© 2021 GitHub, Inc.
